name: Bug Report
description: Create a report to help us improve Xournal++.
labels: bug
body:
    - type: textarea
      attributes:
        label: Operating System (Windows, Mac OS, Linux (distribution))
