name: Bug Report
description: Create a report to help us improve Xournal++.
labels: bug
body:
    - type: dropdown
      attributes:
        label: Operating System
        description: Select the operating system that you use.
        options:
            - Windows
            - Mac OS
            - Linux
      validations:
        required: true
